[package]
name = "libboxer"
version = "0.1.0"
authors = ["Aliaksei Syrel <alex.syrel@gmail.com>"]
edition = "2018"

[dependencies]
boxer = { path = "../boxer" }

[lib]
name = "Boxer"
crate-type = ["cdylib"]
path = "lib.rs"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3