name: Continuous integration
on: [push, pull_request]

jobs:
    build:
        name: Build
        env:
            LIBRARY: Boxer
        runs-on: ${{ matrix.variant.os }}
        strategy:
            matrix:
                variant:
                    - os: ubuntu-18.04
                      artifact: lib$LIBRARY.so
                      deploy: /var/www/html/$LIBRARY/linux/development/x86_64/lib$LIBRARY.so
                    - os: macos-latest
                      artifact: lib$LIBRARY.dylib
                      deploy: /var/www/html/$LIBRARY/osx/development/x86_64/lib$LIBRARY.dylib
                    - os: windows-latest
                      artifact: $LIBRARY.dll
                      deploy: /var/www/html/$LIBRARY/windows/development/x86_64/lib$LIBRARY.dll
        steps:
            - uses: actions/checkout@master
            - name: Install latest stable
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
            - name: Run cargo build
              uses: actions-rs/cargo@v1
              with:
                command: build
                args: --release
            - name: Deploy
              uses: alinz/ssh-scp-action@master
              with:
                  key: ${{ secrets.SSH_KEY }}
                  host: ${{ secrets.FEENK_CLOUD }}
                  
